// Real draft/pinning logic; browser acceptance covers native dialogs and controls.
const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const context=vm.createContext({console, JSON, Date, Map, Set, Object, Array, String,
  document:{readyState:'loading',addEventListener(){}},location:{pathname:'/library'}});
vm.runInContext(fs.readFileSync('foundry.js','utf8'),context);
const run=code=>vm.runInContext(code,context);
run(`work={id:'work-id',revision:'a'.repeat(64),title:'Project',data:{context:'Continue audit',snapshot:{adapter:'json',sessions:[{id:'s1',cwd:'C:/Project',model:'recorded-model',effort:'high',task:'Review release',status:'completed'}]}}}; draft=templateDraft(work)`);
assert.equal(run('draft.model.name'),'recorded-model');
assert.equal(run('draft.provenance.source_work_id'),'work-id');
assert.equal(run('draft.harness.version'),'unrecorded');
assert.equal(run('draft.components.length'),0);
assert.equal(run('draft.resume.handoff'),'Continue audit');
assert.ok(run(`draft.limitations.some(s=>s.includes('unverified'))`));
assert.ok(run(`draft.quality_policy.procedures.includes('human-no-worse-review')`));
run(`draft.components=[{kind:'runbook',ref:'library:old',version:'1',sha256:'a'.repeat(64),rationale:'Original'},{kind:'skill',ref:'library:keep',version:'1',sha256:'b'.repeat(64),rationale:'Keep'}];next={id:'replacement',revision:'c'.repeat(64),kind:'component',data:{component_type:'runbook',version:'2',rationale:'Improve checks'}};candidate=replacePin(draft,0,next)`);
assert.equal(run('candidate.components[0].ref'),'library:replacement');
assert.equal(run('candidate.components[0].sha256'),'c'.repeat(64));
assert.equal(run('candidate.components[1].ref'),'library:keep');
assert.equal(run('draft.components[0].ref'),'library:old','Original manifest must stay immutable');
assert.throws(()=>run(`replacePin(draft,1,next)`),/same component type/);
assert.equal(run(`html('<img onerror="x">')`),'&lt;img onerror=&quot;x&quot;&gt;');
assert.match(run(`sendOutcome({ok:true,code:'queued',status:'finished'})`),/Queued/);
assert.match(run(`sendOutcome({ok:false,code:'provider_failed',status:'finished'})`),/failed/i);
assert.match(run(`sendOutcome({ok:false,code:'provider_timeout',status:'finished',uncertain:true})`),/uncertain/i);
run(`reviewed={id:'same-artifact',kind:'template',revision:'r2',data:{title:'Reviewed draft',review:{candidate_revision:'r1'}}};fresh=reviewCandidatePayload(reviewed)`);
assert.equal(run('fresh.id'),'same-artifact');
assert.equal(run('fresh.expected_revision'),'r2');
assert.equal(run('fresh.manifest.review'),undefined);
assert.equal(run('reviewed.data.review.candidate_revision'),'r1');
run(`next.data.asset={selected:true,license:'CC0'};vendored=pinCandidate(draft,0,next,true)`);
assert.equal(run('vendored.vendor_assets[0].revision'),'c'.repeat(64));
assert.equal(run('vendored.components[1].ref'),'library:keep');
assert.equal(run('draft.vendor_assets'),undefined);
assert.throws(()=>run(`pinCandidate(draft,0,{...next,data:{...next.data,asset:undefined}},true)`),/stored.*license/);
run(`direct={id:'direct',kind:'component',title:'Original title',revision:'a',classification:{revision:'a',display_title:'combat-design',relevance:'direct',kind:'skill',domain:'combat-design',projects:['Enemy Forge'],sources:['skills/combat/SKILL.md'],maturity:['variant','project-specific'],reason:'Direct instructions',evidence:['self:skill'],validation_id:'verified'}};
support={...direct,id:'support',classification:{...direct.classification,relevance:'support'}};
generic={...direct,id:'generic',classification:{...direct.classification,relevance:'generic'}};
uncertain={...direct,id:'uncertain',classification:{...direct.classification,relevance:'uncertain'}};`);
assert(run(`libraryMatches(direct,'','','relevant',{})`));
assert(run(`libraryMatches(support,'','','relevant',{})`));
assert(!run(`libraryMatches(generic,'','','relevant',{})`));
assert(!run(`libraryMatches(uncertain,'','','relevant',{})`));
assert(run(`libraryMatches(uncertain,'','','excluded',{})`));
assert(run(`libraryMatches(generic,'','','all',{})`));
assert(run(`libraryMatches(direct,'SKILLS/COMBAT','component','relevant',{maturity:'variant'})`));
assert(!run(`libraryMatches(direct,'','template','all',{})`));
assert(!run(`libraryMatches(direct,'','','all',{domain:'security'})`));
assert(!run(`libraryMatches({...direct,revision:'new'},'','','relevant',{})`),'Stale classification cannot imply relevance');
assert(run(`libraryMatches({kind:'work',title:'Explicit snapshot'},'','','relevant',{})`));
assert.equal(run(`libraryTitle(direct)`),'combat-design');
assert.equal(run(`libraryTitle({...direct,revision:'new'})`),'Original title');
assert.match(run(`classificationDetails({...direct,classification:{...direct.classification,reason:'<img src=x onerror=bad()>',sources:['<script>']}})`),/&lt;img/);
assert(!run(`classificationDetails({...direct,classification:{...direct.classification,reason:'<script>'}}).includes('<script>')`));
assert.match(run(`classificationDetails(direct)`),/Structural.*functional.*unverified/is);
const manage=fs.readFileSync('manage.html','utf8'),foundrySource=fs.readFileSync('foundry.js','utf8');
for(const path of ['/', '/observatory', '/library', '/settings']) assert(manage.includes(`href="${path}"`));
assert(manage.includes('id="session-actions"'));
assert(manage.includes('href="/foundry.css"'));
assert(!foundrySource.includes("createElement('style')"),'Shared CSS replaces runtime-injected dialog styles');
assert(foundrySource.includes('Save Handoff'));
assert(!/Save live work|Save work snapshot|Save snapshot/i.test(foundrySource));
assert.match(foundrySource,/valid Agent Foundry ZIP/);
assert.match(foundrySource,/arbitrary component file/);
for(const file of ['index.html','observatory.html','manage.html']) assert(fs.readFileSync(file,'utf8').includes('id="help"'),file+' exposes Help');
for(const file of ['index.html','observatory.html','manage.html']) {
  const source=fs.readFileSync(file,'utf8');
  assert(!source.includes('src="/foundry.js"'),file+' relies on the server-owned nonce script injection');
  const ids=[...source.slice(0,source.indexOf('<script>')<0?source.length:source.indexOf('<script>')).matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]);
  assert.equal(new Set(ids).size,ids.length,file+' has unique static element ids');
}
assert.match(run('helpContent()'),/durable handoff plus audit snapshot/);
assert.match(run('helpContent()'),/ingredient.*recipe/is);
assert.match(run('helpContent()'),/hidden.*context/is);
assert.match(run('helpContent()'),/locally untrusted/);
assert.equal(run('draft.harness.id'),'unrecorded','A JSON source adapter is not a harness');
assert.equal(run('draft.provenance.provider'),'unrecorded','A source adapter is not an inference provider');
run(`identityWork={id:'identity',data:{snapshot:{adapter:'json',selected_session_id:'child',sessions:[{id:'root',harness:'codex',provider:'openai',model:'root-model'},{id:'child',parent:'root',harness:'hermes',role:'agent-runtime',provider:'openrouter',model:'independent-model'}]}}};identityDraft=templateDraft(identityWork)`);
assert.equal(run('identityDraft.harness.id'),'hermes');
assert.equal(run('identityDraft.model.name'),'independent-model');
assert.equal(run('identityDraft.provenance.provider'),'openrouter');
run(`componentDetail=libraryDetailMarkup({id:'component',kind:'component',title:'A skill',revision:'a',data:{purpose:'Do useful work',component_type:'skill'}});templateDetail=libraryDetailMarkup({id:'template',kind:'template',title:'A recipe',revision:'b',data:{purpose:'Compose work',components:[],resume:{handoff:'Review first'}}});`);
assert(!run(`componentDetail.includes('Read resume instructions')`),'Components have no resume field');
assert.match(run('templateDetail'),/Agent Template/);
assert.match(run('componentDetail'),/Skill/);
assert.match(run('templateDetail'),/Create upgrade candidate/);
assert.match(run('templateDetail'),/Create candidate with added component/);
assert.match(run('templateDetail'),/Check schema &amp; pinned references/);
assert.match(run('helpContent()'),/Open format status/);
assert.match(run('helpContent()'),/handoffs, Agent Templates and Components/);
assert(!/Test a component upgrade|Pin component…|Names, tags|Confirm promotion of reviewed|Provider send failed/.test(foundrySource));
assert.match(run(`exportInventory({item_count:2,object_count:2,asset_count:0,mode:'reference',inventory:{descriptions:[{title:'<script>record</script>',kind:'component',revision:'a'}],references:[{field:'source_ref',value:'<private>'}]},warnings:['<warning>']})`),/&lt;script&gt;/);
assert.match(run(`exportInventory({inventory:{},warnings:[]})`),/Unverified/);
assert(foundrySource.includes("segments('export-mode'"));
assert(foundrySource.includes("segments('verdict'"));
assert.equal(run('typeof canSendInstruction'),'function','Shared session capability gate must be reusable from worker actions');
run(`foundryBootstrap={configuration:{adapter:'codex'},capabilities:[{adapter:'codex',selected:true,send_followup:true}]}`);
assert(run(`canSendInstruction({id:'live',harness:'codex'})`));
assert(!run(`canSendInstruction({id:'other',harness:'hermes'})`));
assert(!run(`canSendInstruction(null)`));
run(`foundryBootstrap.configuration.adapter='json'`);
assert(!run(`canSendInstruction({id:'live',harness:'codex'})`),'JSON cannot send even when it reports a Codex harness');
assert.match(run(`segments('test','Adapters',[['codex','Codex'],['pi','Pi Agent',true]],'codex')`),/value="pi" disabled/);
assert.equal(run('typeof providerStatusMarkup'),'function');
run(`statusMarkup=providerStatusMarkup({adapter:'json',sessions:[{harness:'hermes',provider:'openrouter',model:'model-x'}],account:{provider:'openai',plan:'<recorded-plan>',token_usage:{total_tokens:0}}})`);
for(const value of ['hermes','openrouter','model-x','openai','&lt;recorded-plan&gt;','0 recorded tokens'])assert(run('statusMarkup').includes(value));
assert.match(run('statusMarkup'),/Sign-in status is not checked/);
assert.match(run('providerStatusMarkup({sessions:[],account:{}})'),/Not reported/);
assert(!run('providerStatusMarkup({sessions:[],account:{}})').includes('0 recorded tokens'),'Missing usage is not zero');
console.log('Foundry UI: honest source drafts, isolated exact-version replacement, escaping, send capability and recorded provider status passed.');
